public class Euler2_EvenFibonacciNumbers {
 static int sum = 2; // 최초 2 값은 현재 구조상 잡을 수 없으므로 최초값 2로 잡음.
	public static void main(String[] args) {

		int[] arr;
		arr = new int[3];
		arr[0] = 1;
		arr[1] = 2;
		arr[2] = arr[0] + arr[1];
		
//		System.out.println(arr[0]);
//		System.out.println(arr[1]);
//		System.out.println(arr[2]);
//		getNextFibonacci(arr);
//		System.out.println(arr[0]);
//		System.out.println(arr[1]);
//		System.out.println(arr[2]);

		do{
		getNextFibonacci(arr);
		}
		while (sum<4*1000000);
			
System.out.println(sum);
		
		
	}

	public static int[] getNextFibonacci(int[] a) {

		a[0] = a[1];
		a[1] = a[2];
		a[2] = a[0] + a[1];
		
		sumIfEvenFibonacci(a);
		return a;
	}
	
	
	public static int sumIfEvenFibonacci(int[] a){
		
		if(a[2]%2==0)
		{
			sum=sum+a[2];
			
		}
		
		return sum;
		
	}
	
	
}
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million,
// find the sum of the even-valued terms.
//